#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#api_login_check:
#    path: /api/login_check



api_login_check:
    path: "/api/login_check"
    defaults: {_format: json}


